import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import record from '../data/topTechStartUps.json'
import BasicCard from './basicCard'
import { useEffect, useState } from 'react'
import Button from '@mui/material/Button';

export default function Home() {
  const [jobs, setJobs] = useState(0); 
  useEffect(() => {
    if(jobs > 133){
      setJobs(0)
    }
},)
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className={styles.main}>
        <div>
        <div className='logoContainer'>
          <img className='logo' src="topstartups.png" alt="" srcSet="" />
        </div>
        <a href="info" className='allJobsLink'>see all jobs</a>
        </div>
        <div className='cardSectionContainer' id='colourContainer'>
          {
            record.slice(jobs,jobs+6).map((e) => <div key={e.id} className='cardContainer'>
              <BasicCard className='basicCard' companyName={e.company_name} headline={e.headline} location={e.locations} website={e.website}/>
            </div>)
          }
        <div className='buttonSection'>
          <div className='buttonContainer'>
            <Button onClick={() => ((jobs > 0)? setJobs(jobs-6): setJobs(0))} variant="contained">Back</Button>
          </div>
          <div className='buttonContainer'>
            <Button onClick={() => setJobs(jobs+6)} variant="contained">Next</Button>
          </div>
        </div>
        </div>
      </main>
    </>
  )
}
