import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import record from '../data/topTechStartUps.json'
import BasicCard from './basicCard'
import { useState } from 'react'
import Info from './info'
import { useRouter } from 'next/router'
import Stack from '@mui/material/Stack';
import Button from '@mui/material/Button';

export default function Home() {
  const router = useRouter()
  const [jobs, setJobs] = useState(0); 
  const handleClick = () => {
    router.push("info")
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className={styles.main}>
        <h1>About Page</h1>
        <div className='logoContainer'>
          <img className='logo' src="topstartups.png" alt="" srcSet="" />
        </div>
        <a href="info">see all jobs</a>
        <div className='cardSectionContainer'>
          {
            record.slice(jobs,jobs+6).map((e) => <div key={e.id} className='cardContainer'>
              <BasicCard className='basicCard' companyName={e.company_name} headline={e.headline} location={e.locations} website={e.website}/>
            </div>)
          }
        <div>
          <Button onClick={() => ((jobs > 0)? setJobs(jobs-6): setJobs(0))} variant="contained">Back</Button>
          <Button onClick={() => setJobs(jobs+6)} variant="contained">Next</Button>
        </div>
        </div>
      </main>
    </>
  )
}
